### ISSUE TITLE
Sync device time

### ISSUE THREAD

**Issue by bobans** [theIoTLab/ZephyrBHDeviceAdapter#2]
Add option (command) to set device time.

**Comment by marcello-morena** [comment]
Although setting device time seems to be possible via Bluetooth and USB, as far as we know there is no way to do this using the Zephyr Android library. Since we use the Android library to handle low level bluetooth communication with the BioHarness 3, we cannot add this functionality. You could use the Zephyr Cfg Tool on a Windows PC to set the device time before you start using the BioHarness 3 with the Device Adapter. You should need to do this only once, or at least once in a while.
